name = "BioSequences"
uuid = "7e6ae17a-c86d-528c-b3b9-7f778a29fe59"
authors = ["Sabrina Jaye Ward <sabrinajward@protonmail.com>", "Jakob Nissen <jakobnybonissen@gmail.com>"]
version = "3.1.6"

[deps]
BioSymbols = "3c28c6f8-a34d-59c4-9654-267d177fcfa9"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
Twiddle = "7200193e-83a8-5a55-b20d-5d36d44a0795"

[compat]
BioSymbols = "5.1.2"
PrecompileTools = "1"
Random = "1.5"
StableRNGs = "0.1, 1.0"
Twiddle = "1.1.1"
julia = "1.5"

[extras]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"

[targets]
test = ["Documenter", "Test", "StatsBase", "YAML", "LinearAlgebra", "StableRNGs"]
