name = "BioSequences"
uuid = "7e6ae17a-c86d-528c-b3b9-7f778a29fe59"
authors = ["Ben J. Ward <benjward@protonmail.com>"]
version = "2.0.5"

[deps]
BioGenerics = "47718e42-2ac5-11e9-14af-e5595289c2ea"
BioSymbols = "3c28c6f8-a34d-59c4-9654-267d177fcfa9"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
IndexableBitVectors = "1cb3b9ac-1ffd-5777-9e6b-a3d42300664d"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"
Twiddle = "7200193e-83a8-5a55-b20d-5d36d44a0795"

[compat]
BioGenerics = "0.1.0"
BioSymbols = "4.0.0"
Combinatorics = "1.0.0"
IndexableBitVectors = "1.0.0"
StableRNGs = "0.1, 1.0"
Twiddle = "1.1.1"
julia = "1"

[extras]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"

[targets]
test = ["Test", "StatsBase", "YAML", "LinearAlgebra"]
